-- ============================================================
-- File: .kiro/skills/sql-reporting/scripts/fixtures/reporting_seed.sql
-- Description: Extra deterministic data for the sql-reporting self-test, loaded
--              AFTER the sql-conversion sample seed (orders 1-8 exist already).
--              Generated from scripts/fixtures/reporting_seed.py-data; expected
--              test values were computed independently in Python.
-- ============================================================

INSERT INTO public.orders (order_id, customer_id, total_amount, status, created_at) VALUES
    (9, 1, 99.94, 'Completed', '2025-01-05 09:15:00'),
    (10, 2, 199.96, 'Completed', '2025-01-20 17:40:00'),
    (11, 3, 149.94, 'Completed', '2025-02-14 12:00:00'),
    (12, 1, 299.97, 'Cancelled', '2025-03-03 08:00:00'),
    (13, 4, 49.95, 'Completed', '2025-03-30 23:59:59'),
    (14, 5, 399.96, 'Completed', '2025-04-01 00:00:00'),
    (15, 1, 249.95, 'Completed', '2025-05-15 10:00:00'),
    (16, 2, 119.96, 'Refunded', '2025-07-04 10:00:00'),
    (17, 3, 159.94, 'Completed', '2025-08-08 08:08:08'),
    (18, 4, 69.93, 'Completed', '2025-10-10 10:10:10'),
    (19, 5, 199.92, 'Completed', '2025-11-11 11:11:11'),
    (20, 1, 499.95, 'Completed', '2025-12-31 23:59:59'),
    (21, 2, 29.99, 'Completed', '2025-06-30 18:30:00'),
    (22, 3, 99.98, 'Completed', '2025-09-21 07:00:00'),
    (23, 4, 89.97, 'Completed', '2025-12-01 12:00:00');
SELECT setval(pg_get_serial_sequence('public.orders','order_id'), (SELECT MAX(order_id) FROM public.orders));

INSERT INTO public.order_lines (order_id, product_id, quantity, unit_price, line_total) VALUES
    (9, 1, 2, 29.99, 59.98),
    (9, 4, 4, 9.99, 39.96),
    (10, 2, 4, 49.99, 199.96),
    (11, 5, 1, 99.99, 99.99),
    (11, 4, 5, 9.99, 49.95),
    (12, 5, 3, 99.99, 299.97),
    (13, 4, 5, 9.99, 49.95),
    (14, 5, 4, 99.99, 399.96),
    (15, 2, 5, 49.99, 249.95),
    (16, 1, 4, 29.99, 119.96),
    (17, 1, 5, 29.99, 149.95),
    (17, 4, 1, 9.99, 9.99),
    (18, 4, 7, 9.99, 69.93),
    (19, 2, 3, 49.99, 149.97),
    (19, 4, 5, 9.99, 49.95),
    (20, 5, 5, 99.99, 499.95),
    (21, 1, 1, 29.99, 29.99),
    (22, 2, 2, 49.99, 99.98),
    (23, 1, 3, 29.99, 89.97);

-- Daily stock snapshots (semi-additive measure: balances are NOT summed over time)
CREATE TABLE IF NOT EXISTS public.inventory_snapshots (
    snapshot_date     DATE    NOT NULL,
    product_id        INTEGER NOT NULL,
    warehouse_id      INTEGER NOT NULL,
    quantity_on_hand  INTEGER NOT NULL,
    PRIMARY KEY (snapshot_date, product_id, warehouse_id)
);
INSERT INTO public.inventory_snapshots VALUES
    ('2025-06-01', 1, 1, 40), ('2025-06-15', 1, 1, 55), ('2025-06-30', 1, 1, 50),
    ('2025-06-01', 2, 1, 5),  ('2025-06-20', 2, 1, 3),
    ('2025-07-01', 1, 1, 48), ('2025-07-31', 1, 1, 60), ('2025-07-31', 2, 1, 9);

-- Web funnel events for the funnel pattern
CREATE TABLE IF NOT EXISTS public.web_events (
    event_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    event_type  VARCHAR(20) NOT NULL,   -- view | cart | checkout | purchase
    event_at    TIMESTAMP NOT NULL
);
INSERT INTO public.web_events (customer_id, event_type, event_at) VALUES
    (1,'view','2025-06-01 10:00'),(1,'cart','2025-06-01 10:05'),(1,'checkout','2025-06-01 10:07'),(1,'purchase','2025-06-01 10:09'),
    (2,'view','2025-06-02 09:00'),(2,'cart','2025-06-02 09:10'),
    (3,'view','2025-06-03 11:00'),(3,'view','2025-06-03 11:30'),(3,'cart','2025-06-03 11:40'),(3,'checkout','2025-06-03 11:45'),
    (4,'view','2025-06-04 12:00'),
    (5,'view','2025-06-05 13:00'),(5,'cart','2025-06-05 13:02'),(5,'checkout','2025-06-05 13:05'),(5,'purchase','2025-06-05 13:06'),
    (5,'view','2025-06-06 13:00');
