-- Generated by iceberg_tool.py ddl v1.0.0 on 2026-09-18T17:55:28.115Z — dialect athena
-- Source sha256 25754ab5fed2cc990f704bd65c4804d5b550991ab0fe5a1c32b43c00a98c5bac
-- Rules: .kiro/steering/iceberg.md · ledger in the conversion package

CREATE TABLE sales_lake.dim_customer (
    customer_key int,
    customer_id string COMMENT 'source: UNIQUEIDENTIFIER',
    customer_name string COMMENT 'source: NVARCHAR(200)',
    region string COMMENT 'source: VARCHAR(50)',
    is_active boolean,
    notes string COMMENT 'source: NVARCHAR(MAX)',
    created_at timestamp COMMENT 'source: DATETIME2(3)'
)
LOCATION 's3://example-lake-bucket/sales_lake/dim_customer/'
TBLPROPERTIES ('table_type'='ICEBERG', 'format'='parquet', 'write_compression'='zstd', 'write.delete.mode'='merge-on-read', 'write.update.mode'='merge-on-read', 'write.merge.mode'='merge-on-read');
-- identity customer_key: generated by the load job, not by the table (IB-01)
-- default customer_id = NEWID(): applied in the load job (IB-03)
-- default is_active = 1: applied in the load job (IB-03)
-- default created_at = SYSDATETIME(): applied in the load job (IB-03)
-- PRIMARY KEY PK_DimCustomer: not declared in Iceberg DDL; validated by query (IB-02)
-- CHECK CK_DimCustomer_Region: not declared in Iceberg DDL; validated by query (IB-02)
-- index UX_DimCustomer_Name on (customer_name): WRITE ORDERED BY candidate (IB-05)

CREATE TABLE sales_lake.fact_sales (
    sales_key bigint,
    customer_key int,
    sale_date date,
    quantity int COMMENT 'source: SMALLINT',
    unit_price decimal(19,4) COMMENT 'source: MONEY',
    loaded_at timestamp COMMENT 'source: DATETIME'
)
PARTITIONED BY (day(sale_date), bucket(16, customer_key))
LOCATION 's3://example-lake-bucket/sales_lake/fact_sales/'
TBLPROPERTIES ('table_type'='ICEBERG', 'format'='parquet', 'write_compression'='zstd');
-- identity sales_key: generated by the load job, not by the table (IB-01)
-- TODO: MANUAL REVIEW REQUIRED — computed column line_total AS (Quantity * UnitPrice) PERSISTED: compute it in the load job (IB-04)
-- default loaded_at = GETDATE(): applied in the load job (IB-03)
-- PRIMARY KEY PK_FactSales: not declared in Iceberg DDL; validated by query (IB-02)
-- FOREIGN KEY FK_FactSales_Customer: not declared in Iceberg DDL; validated by query (IB-02)
-- index IX_FactSales_SaleDate on (sale_date, customer_key): WRITE ORDERED BY candidate (IB-05)
