#!/usr/bin/env python3
"""
Generate the Windows twins (run_skill_tests.ps1 + run_skill_tests.cmd) for skills whose self-test
is "run the Python unit tests, then check catalog coverage" (no database step).

  python3 supporting-files/make_skill_runners.py            # (re)write twins for every skill with a skill.runner.json
  python3 supporting-files/make_skill_runners.py --check    # exit 1 when a twin is out of date

Each such skill declares its runner in scripts/skill.runner.json:
  {"tests": ["tests/test_x.py"], "catalog": "../references/x.md", "prefixes": ["XX"], "label": "x"}
The bash runner is hand-written (it is the reference); the PowerShell twin is generated from the same
declaration so both stay aligned. Skills with a PostgreSQL step keep hand-written twins.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILLS = ROOT / ".kiro" / "skills"

PS1 = """<#
.SYNOPSIS
  {name} skill — self-test (Windows version of run_skill_tests.sh; generated by supporting-files\\make_skill_runners.py).
.DESCRIPTION
  Runs the Python unit tests {tests} and checks that every catalog row ({prefixes}) has a tagged test.
#>
$ErrorActionPreference = 'Continue'
$Scripts = $PSScriptRoot
$Engine = Join-Path $Scripts '..\\..\\sql-conversion\\scripts'
if (-not (Test-Path (Join-Path $Engine 'winlib.ps1'))) {{ Write-Error "shared engine not found at $Engine (install the sql-conversion skill)"; exit 2 }}
. (Join-Path $Engine 'winlib.ps1')
$Results = [IO.Path]::GetTempFileName()
try {{
    $unit = 0
{test_lines}
    Invoke-MigPython -ArgList @((Join-Path $Engine 'check_rule_coverage.py'), '--results', $Results, '--no-steering', '--catalog', (Join-Path $Scripts '{catalog}'){prefix_args}); $cov = $LASTEXITCODE
    if ($unit -eq 0 -and $cov -eq 0) {{ Write-Host 'SKILL SELF-TEST: PASS'; exit 0 }}
    [Console]::Error.WriteLine("SKILL SELF-TEST: FAIL (unit $unit, coverage $cov)")
    exit 1
}} finally {{
    Remove-Item -LiteralPath $Results -ErrorAction SilentlyContinue
}}
"""
CMD = ("@echo off\r\nrem Windows launcher for run_skill_tests.ps1 (same arguments as run_skill_tests.sh). Usage: run_skill_tests.cmd\r\n"
       "setlocal\r\nwhere pwsh >nul 2>nul\r\nif %ERRORLEVEL%==0 (\r\n    pwsh -NoProfile -ExecutionPolicy Bypass -File \"%~dp0run_skill_tests.ps1\" %*\r\n"
       ") else (\r\n    powershell -NoProfile -ExecutionPolicy Bypass -File \"%~dp0run_skill_tests.ps1\" %*\r\n)\r\nexit /b %ERRORLEVEL%\r\n")


def render(skill: str, decl: dict) -> str:
    test_lines = "\n".join(
        f"    Invoke-MigPython -ArgList @((Join-Path $Scripts '{t.replace('/', chr(92))}'), '--results', $Results); if ($LASTEXITCODE -ne 0) {{ $unit = 1 }}"
        for t in decl["tests"])
    prefix_args = "".join(f", '--prefix', '{p}'" for p in decl["prefixes"])
    body = PS1.format(name=skill, tests=", ".join(decl["tests"]), prefixes="/".join(decl["prefixes"]), test_lines=test_lines,
                      catalog=decl["catalog"].replace("/", "\\"), prefix_args=prefix_args)
    return "﻿" + body.replace("\n", "\r\n")


def main():
    check = "--check" in sys.argv
    stale = []
    for decl_file in sorted(SKILLS.glob("*/scripts/skill.runner.json")):
        skill = decl_file.parents[1].name
        decl = json.loads(decl_file.read_text(encoding="utf-8"))
        ps1 = decl_file.parent / "run_skill_tests.ps1"; cmd = decl_file.parent / "run_skill_tests.cmd"
        want_ps1, want_cmd = render(skill, decl).encode("utf-8"), CMD.encode("ascii")
        if check:
            if not ps1.exists() or ps1.read_bytes() != want_ps1 or not cmd.exists() or cmd.read_bytes() != want_cmd:
                stale.append(skill)
        else:
            ps1.write_bytes(want_ps1); cmd.write_bytes(want_cmd); print(f"wrote {ps1} and {cmd.name}")
    if check and stale:
        print("stale Windows runners: " + ", ".join(stale) + " — run python3 supporting-files/make_skill_runners.py", file=sys.stderr)
        return 1
    if check:
        print("windows skill runners up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
