<#
.SYNOPSIS
  schema-conformance skill — self-test (Windows version of run_skill_tests.sh; generated by supporting-files\make_skill_runners.py).
.DESCRIPTION
  Runs the Python unit tests tests/test_schema_tool.py and checks that every catalog row (SC) has a tagged test.
#>
$ErrorActionPreference = 'Continue'
$Scripts = $PSScriptRoot
$Engine = Join-Path $Scripts '..\..\sql-conversion\scripts'
if (-not (Test-Path (Join-Path $Engine 'winlib.ps1'))) { Write-Error "shared engine not found at $Engine (install the sql-conversion skill)"; exit 2 }
. (Join-Path $Engine 'winlib.ps1')
$Results = [IO.Path]::GetTempFileName()
try {
    $unit = 0
    Invoke-MigPython -ArgList @((Join-Path $Scripts 'tests\test_schema_tool.py'), '--results', $Results); if ($LASTEXITCODE -ne 0) { $unit = 1 }
    Invoke-MigPython -ArgList @((Join-Path $Engine 'check_rule_coverage.py'), '--results', $Results, '--no-steering', '--catalog', (Join-Path $Scripts '..\references\conformance-rules.md'), '--prefix', 'SC'); $cov = $LASTEXITCODE
    if ($unit -eq 0 -and $cov -eq 0) { Write-Host 'SKILL SELF-TEST: PASS'; exit 0 }
    [Console]::Error.WriteLine("SKILL SELF-TEST: FAIL (unit $unit, coverage $cov)")
    exit 1
} finally {
    Remove-Item -LiteralPath $Results -ErrorAction SilentlyContinue
}
