#!/usr/bin/env python3
"""Unit tests for schema_tool.py. Docstrings carry the [SC-nn] tags proven; results are appended to
--results FILE as "STATUS<TAB>schema<TAB>name" for check_rule_coverage.py. No database needed; a live
PostgreSQL comparison runs only when PGHOST/PGDATABASE point at a test database."""
import argparse
import contextlib
import io
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile
import unittest

if os.name == "nt" and not sys.flags.utf8_mode:
    import subprocess as _sp
    os.environ["PYTHONUTF8"] = "1"
    sys.exit(_sp.call([sys.executable, "-X", "utf8", *sys.argv]))

SCRIPTS = pathlib.Path(__file__).resolve().parents[1]
SKILL = SCRIPTS.parent
ROOT = SKILL.parents[2]
ENGINE = SKILL.parent / "sql-conversion" / "scripts"
STUB = ENGINE / "tests" / "stub" / ("aws.cmd" if os.name == "nt" else "aws")
_STATE = pathlib.Path(tempfile.mkdtemp(prefix="schema-test-"))
os.environ["MIGRATION_LOG_DIR"] = str(_STATE / "audit"); os.environ["MIGRATION_STATE_DIR"] = str(_STATE / "state")
os.environ["MIGRATION_OFFLINE"] = "1"; os.environ.setdefault("MIGRATION_RUN_ID", "4df7651916cd43dd8448eb211c80319f")
sys.path.insert(0, str(SCRIPTS))
import schema_tool as tool  # noqa: E402

SRC = """CREATE TABLE [dbo].[OrderLines] (
    [OrderLineId] BIGINT IDENTITY(1,1) NOT NULL,
    [OrderId]     INT NOT NULL,
    [Quantity]    SMALLINT NOT NULL,
    [UnitPrice]   MONEY NOT NULL,
    [Note]        NVARCHAR(200) NULL,
    [CreatedAt]   DATETIME2 NOT NULL CONSTRAINT DF_OL DEFAULT SYSDATETIME(),
    [LineTotal]   AS (Quantity * UnitPrice) PERSISTED,
    [Tag]         VARCHAR(MAX) NULL,
    CONSTRAINT PK_OrderLines PRIMARY KEY CLUSTERED ([OrderLineId]),
    CONSTRAINT UQ_OrderLines UNIQUE ([OrderId], [Quantity])
);
CREATE TABLE [dbo].[Legacy] ([Id] INT NOT NULL PRIMARY KEY, [Payload] SQL_VARIANT NULL);
"""
TGT_OK = """CREATE TABLE public.order_lines (
    order_line_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id      INTEGER NOT NULL,
    quantity      SMALLINT NOT NULL,
    unit_price    NUMERIC(19,4) NOT NULL,
    note          VARCHAR(200),
    created_at    TIMESTAMP NOT NULL DEFAULT clock_timestamp(),
    line_total    NUMERIC(24,4) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    tag           TEXT,
    CONSTRAINT pk_order_lines PRIMARY KEY (order_line_id),
    CONSTRAINT uq_order_lines UNIQUE (order_id, quantity)
);
CREATE TABLE public.legacy (id INTEGER NOT NULL PRIMARY KEY, payload JSONB);
"""
TGT_BAD = """CREATE TABLE public.order_lines (
    order_line_id INTEGER NOT NULL,
    order_id      INTEGER NOT NULL,
    quantity      SMALLINT NOT NULL,
    unit_price    NUMERIC(19,2) NOT NULL,
    note          VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    tag           VARCHAR(255),
    extra_flag    BOOLEAN,
    _run_id       VARCHAR(32),
    CONSTRAINT pk_order_lines PRIMARY KEY (order_id)
);
CREATE TABLE public.audit_only (id INTEGER);
"""


def run(cmd, *args):
    buf, err = io.StringIO(), io.StringIO()
    with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(err):
        old = sys.argv
        try:
            sys.argv = ["schema_tool.py", cmd, *args]
            rc = tool.main()
        except SystemExit as ex:
            rc = ex.code
        finally:
            sys.argv = old
    return rc, buf.getvalue() + err.getvalue()


def rows(cmp, table="dbo.orderlines"):
    return {(r["source"] or "→" + r["target"]): r for r in cmp["tables"][table]["columns"]}


class SchemaTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = pathlib.Path(tempfile.mkdtemp(prefix="schema-"))
        cls.src = tool.snapshot_from_ddl(SRC, "tsql", "fixture.sqlserver.sql")
        cls.ok = tool.snapshot_from_ddl(TGT_OK, "pgsql", "fixture.postgres.sql")
        cls.bad = tool.snapshot_from_ddl(TGT_BAD, "pgsql", "fixture.bad.sql")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmp, ignore_errors=True)

    def test_snapshot_from_ddl(self):
        """SC-T01 canonical snapshots from T-SQL, PostgreSQL, Redshift and Spark DDL carry provenance, a content hash independent of capture time, keys, identity, defaults, computed columns and unverified items [SC-01] [SC-04]"""
        s = self.src
        self.assertEqual(s["provenance"]["method"], "ddl-parse"); self.assertEqual(s["provenance"]["dialect"], "tsql"); self.assertEqual(len(s["provenance"]["sha256"]), 64)
        t = s["tables"]["dbo.orderlines"]
        self.assertEqual(t["name"], "OrderLines"); self.assertEqual(t["primaryKey"], ["OrderLineId"]); self.assertEqual(t["unique"], [["OrderId", "Quantity"]])
        c = {x["name"]: x for x in t["columns"]}
        self.assertTrue(c["OrderLineId"]["identity"]); self.assertEqual(c["UnitPrice"]["type"]["base"], "money"); self.assertEqual(c["Tag"]["type"]["length"], "MAX")
        self.assertIsNotNone(c["CreatedAt"]["default"]); self.assertTrue(c["LineTotal"]["computed"]); self.assertEqual(c["Note"]["ordinal"], 5)
        again = tool.snapshot_from_ddl(SRC, "tsql", "other-name.sql")
        self.assertEqual(again["hash"], s["hash"], "hash depends on content only")
        pg = self.ok["tables"]["public.order_lines"]; pc = {x["name"]: x for x in pg["columns"]}
        self.assertTrue(pc["order_line_id"]["identity"]); self.assertEqual(pc["unit_price"]["type"], {"base": "decimal", "length": None, "precision": 19, "scale": 4, "raw": "NUMERIC(19,4)"})
        self.assertEqual(pc["tag"]["type"]["base"], "text"); self.assertTrue(pc["line_total"]["computed"])
        rs = tool.snapshot_from_ddl("CREATE TABLE sales.f (id BIGINT IDENTITY(1,1) NOT NULL, n VARCHAR(65535), b VARBYTE(8), CONSTRAINT pk PRIMARY KEY (id)) DISTSTYLE KEY DISTKEY(id) COMPOUND SORTKEY(id);", "redshift")
        self.assertEqual(rs["tables"]["sales.f"]["distribution"].get("distkey"), "id"); self.assertEqual({c["name"]: c["type"]["base"] for c in rs["tables"]["sales.f"]["columns"]}["b"], "varbyte")
        sp = tool.snapshot_from_ddl("CREATE TABLE glue_catalog.lake.f (id bigint NOT NULL, n string COMMENT 'source: NVARCHAR(200)', ts timestamp) USING iceberg PARTITIONED BY (days(ts)) TBLPROPERTIES ('format-version'='2');", "spark")
        self.assertEqual(sp["tables"]["lake.f"]["partition"], ["days(ts)"]); self.assertEqual({c["name"]: c["type"]["base"] for c in sp["tables"]["lake.f"]["columns"]}["n"], "string")
        odd = tool.snapshot_from_ddl("CREATE TABLE dbo.X (Id INT NOT NULL, Secret NVARCHAR(50) MASKED WITH (FUNCTION = 'default()') NULL);", "tsql")
        col = {c["name"]: c for c in odd["tables"]["dbo.x"]["columns"]}["Secret"]
        self.assertTrue(col["unverified"], "unparsed column options are recorded, not dropped")
        cmp = tool.compare(odd, tool.snapshot_from_ddl("CREATE TABLE public.x (id INTEGER NOT NULL, secret VARCHAR(50));", "pgsql"))
        self.assertEqual(rows(cmp, "dbo.x")["Secret"]["classification"], "UNVERIFIED"); self.assertEqual(cmp["status"], "PARTIAL"); self.assertEqual(cmp["stopCodes"], ["METADATA_AMBIGUOUS"])

    def test_live_snapshot_builder_and_gating(self):
        """SC-T02 live PostgreSQL snapshot: information_schema query per schema, rows mapped to the canonical form (aliases, precision, identity), non-test databases refused, token never logged [SC-02]"""
        q = tool.live_query("public"); self.assertIn("information_schema.columns", q); self.assertIn("table_schema = 'public'", q)
        with self.assertRaises(SystemExit):
            tool.live_query("public; drop table x")
        rows_ = [{"table_schema": "public", "table_name": "order_lines", "primary_key": ["order_line_id"], "uniques": [["order_id", "quantity"]],
                  "columns": [{"name": "order_line_id", "ordinal": 1, "data_type": "bigint", "udt": "int8", "length": None, "precision": 64, "scale": 0, "dt_precision": None, "nullable": False, "default": None, "identity": True, "generated": None},
                              {"name": "note", "ordinal": 2, "data_type": "character varying", "udt": "varchar", "length": 200, "precision": None, "scale": None, "dt_precision": None, "nullable": True, "default": None, "identity": False, "generated": None},
                              {"name": "unit_price", "ordinal": 3, "data_type": "numeric", "udt": "numeric", "length": None, "precision": 19, "scale": 4, "dt_precision": None, "nullable": False, "default": None, "identity": False, "generated": None},
                              {"name": "created_at", "ordinal": 4, "data_type": "timestamp without time zone", "udt": "timestamp", "length": None, "precision": None, "scale": None, "dt_precision": 3, "nullable": False, "default": "now()", "identity": False, "generated": None},
                              {"name": "tags", "ordinal": 5, "data_type": "ARRAY", "udt": "_text", "length": None, "precision": None, "scale": None, "dt_precision": None, "nullable": True, "default": None, "identity": False, "generated": None}]}]
        snap = tool.snapshot_from_live_rows(rows_, "sql_migration_test", "db.example")
        self.assertEqual(snap["provenance"]["method"], "live-information_schema")
        c = {x["name"]: x for x in snap["tables"]["public.order_lines"]["columns"]}
        self.assertEqual(c["note"]["type"]["base"], "varchar"); self.assertEqual(c["note"]["type"]["length"], 200)
        self.assertEqual(c["unit_price"]["type"]["precision"], 19); self.assertEqual(c["created_at"]["type"]["base"], "timestamp"); self.assertEqual(c["created_at"]["type"]["precision"], 3)
        self.assertTrue(c["order_line_id"]["identity"]); self.assertEqual(c["tags"]["type"]["base"], "text[]")
        old = os.environ.get("PGDATABASE"); os.environ["PGDATABASE"] = "sales_prod"
        try:
            rc, out = run("snapshot", "--live", "--out", str(self.tmp / "live.json")); self.assertEqual(rc, 3, out)
        finally:
            if old is None:
                os.environ.pop("PGDATABASE")
            else:
                os.environ["PGDATABASE"] = old
        src = pathlib.Path(tool.__file__).read_text(encoding="utf-8")
        self.assertIn("never logged", src); self.assertNotIn("PGPASSWORD=", src.replace('env["PGPASSWORD"] = tok', ""))

    def test_glue_snapshot(self):
        """SC-T03 Glue Data Catalog snapshot through the AWS layer (stub CLI): Iceberg table properties, decimal precision, unknown types unverified, non-test databases refused [SC-03]"""
        cfg = self.tmp / "services.json"; cfg.write_text(json.dumps({"aws_cli": str(STUB), "region": "us-east-1", "probe_cache_seconds": 0}))
        env = {"MIGRATION_SERVICES_CONFIG": str(cfg), "STUB_LOG": str(self.tmp / "stub.jsonl"), "STUB_SCENARIO": "ok"}
        old = {k: os.environ.get(k) for k in ("MIGRATION_OFFLINE", *env)}
        os.environ.pop("MIGRATION_OFFLINE", None); os.environ.update(env)
        try:
            rc, out = run("snapshot", "--glue", "--database", "sales_prod", "--out", str(self.tmp / "g.json")); self.assertEqual(rc, 3, out)
            rc, out = run("snapshot", "--glue", "--database", "sales_lake_dev", "--out", str(self.tmp / "g.json")); self.assertEqual(rc, 0, out)
        finally:
            for k, v in old.items():
                if v is None:
                    os.environ.pop(k, None)
                else:
                    os.environ[k] = v
        g = json.loads((self.tmp / "g.json").read_text(encoding="utf-8"))
        t = g["tables"]["sales_lake_dev.order_lines"]; self.assertEqual(t["properties"]["table_type"], "ICEBERG")
        c = {x["name"]: x for x in t["columns"]}; self.assertEqual(c["unit_price"]["type"], {"base": "decimal", "length": None, "precision": 19, "scale": 4, "raw": "decimal(19,4)"})
        self.assertEqual(c["order_id"]["type"]["base"], "integer")
        odd = tool.snapshot_from_glue([{"Name": "t", "StorageDescriptor": {"Columns": [{"Name": "m", "Type": "map<string,int>"}]}}], "lake_dev")
        self.assertTrue(odd["tables"]["lake_dev.t"]["columns"][0]["unverified"])
        cmp = tool.compare(self.src, g, "iceberg")
        self.assertEqual(rows(cmp)["_run_id" if "_run_id" in rows(cmp) else "→_run_id"]["classification"], "APPROVED_TRANSFORM")

    def test_classification_matrix(self):
        """SC-T04 EXACT, APPROVED_TRANSFORM, MISSING_TARGET, MISSING_SOURCE with technical columns, type CONFLICT, narrowing CONFLICT, nullability, identity/default/computed notes [SC-10] [SC-11] [SC-12] [SC-13] [SC-14] [SC-15] [SC-16] [SC-18]"""
        good = tool.compare(self.src, self.ok, "aurora"); r = rows(good)
        self.assertEqual(r["OrderId"]["classification"], "EXACT"); self.assertEqual(r["Quantity"]["classification"], "EXACT")
        self.assertEqual(r["UnitPrice"]["classification"], "APPROVED_TRANSFORM"); self.assertIn("MONEY → NUMERIC(19,4)", r["UnitPrice"]["reason"])
        self.assertEqual(r["Note"]["classification"], "APPROVED_TRANSFORM"); self.assertEqual(r["Tag"]["classification"], "APPROVED_TRANSFORM")
        self.assertEqual(r["OrderLineId"]["classification"], "EXACT"); self.assertEqual(r["LineTotal"]["classification"], "APPROVED_TRANSFORM"); self.assertIn("computed column kept", r["LineTotal"]["reason"])
        self.assertEqual(rows(good, "dbo.legacy")["Payload"]["classification"], "APPROVED_TRANSFORM")
        ident = rows(tool.compare(self.src, tool.snapshot_from_ddl(TGT_OK.replace("GENERATED BY DEFAULT AS IDENTITY ", ""), "pgsql"), "aurora"))["OrderLineId"]
        self.assertEqual(ident["classification"], "APPROVED_TRANSFORM"); self.assertIn("identity dropped", ident["reason"])
        self.assertEqual(good["summary"]["CONFLICT"], 0); self.assertEqual(good["status"], "GENERATED")
        bad = tool.compare(self.src, self.bad, "aurora"); r = rows(bad)
        self.assertEqual(r["OrderLineId"]["classification"], "CONFLICT"); self.assertIn("narrowing bigint", r["OrderLineId"]["reason"])
        self.assertEqual(r["UnitPrice"]["classification"], "CONFLICT"); self.assertIn("scale", r["UnitPrice"]["reason"])
        self.assertEqual(r["Note"]["classification"], "CONFLICT"); self.assertIn("tightened", r["Note"]["reason"])
        self.assertEqual(r["Tag"]["classification"], "CONFLICT"); self.assertIn("MAX", r["Tag"]["reason"])
        self.assertEqual(r["LineTotal"]["classification"], "MISSING_TARGET")
        self.assertEqual(r["→extra_flag"]["classification"], "MISSING_SOURCE"); self.assertEqual(r["→_run_id"]["classification"], "APPROVED_TRANSFORM")
        self.assertEqual(r["CreatedAt"]["classification"], "APPROVED_TRANSFORM"); self.assertIn("default dropped", r["CreatedAt"]["reason"])
        # type not in the allowlist
        wrong = tool.snapshot_from_ddl("CREATE TABLE public.order_lines (order_line_id BIGINT NOT NULL, order_id INTEGER NOT NULL, quantity SMALLINT NOT NULL, unit_price DOUBLE PRECISION NOT NULL, note VARCHAR(200), created_at TIMESTAMP NOT NULL, tag TEXT);", "pgsql")
        w = rows(tool.compare(self.src, wrong, "aurora"))
        self.assertEqual(w["UnitPrice"]["classification"], "CONFLICT"); self.assertIn("not approved", w["UnitPrice"]["reason"])
        # relaxed nullability is approved with a warning
        rel = tool.snapshot_from_ddl("CREATE TABLE public.legacy (id INTEGER, payload TEXT);", "pgsql")
        rr = rows(tool.compare(self.src, rel, "aurora"), "dbo.legacy")
        self.assertEqual(rr["Id"]["classification"], "APPROVED_TRANSFORM"); self.assertIn("relaxed", rr["Id"]["reason"])

    def test_profiles(self):
        """SC-T05 the Redshift and Iceberg allowlists differ from Aurora (TEXT rejected on Redshift, varchar(n) rejected on Iceberg, string/binary accepted, informational keys) [SC-11] [SC-14] [SC-17]"""
        rs = tool.snapshot_from_ddl("CREATE TABLE public.order_lines (order_line_id BIGINT IDENTITY(1,1) NOT NULL, order_id INTEGER NOT NULL, quantity SMALLINT NOT NULL, unit_price DECIMAL(19,4) NOT NULL, note VARCHAR(800), created_at TIMESTAMP NOT NULL, line_total DECIMAL(24,4), tag VARCHAR(65535), PRIMARY KEY (order_line_id));\nCREATE TABLE public.legacy (id INTEGER NOT NULL, payload SUPER);", "redshift")
        c = tool.compare(self.src, rs, "redshift"); r = rows(c)
        self.assertEqual(r["Note"]["classification"], "APPROVED_TRANSFORM"); self.assertEqual(r["Tag"]["classification"], "APPROVED_TRANSFORM"); self.assertEqual(rows(c, "dbo.legacy")["Payload"]["classification"], "APPROVED_TRANSFORM")
        self.assertEqual(c["status"], "GENERATED")
        keys = [k for k in c["keyFindings"] if k["table"] == "dbo.orderlines"]
        self.assertTrue(keys and all(k["classification"] == "APPROVED_TRANSFORM" for k in keys), keys)  # unique missing → informational
        bad = tool.snapshot_from_ddl("CREATE TABLE public.legacy (id INTEGER NOT NULL, payload TEXT);", "redshift")
        self.assertEqual(rows(tool.compare(self.src, bad, "redshift"), "dbo.legacy")["Payload"]["classification"], "CONFLICT")
        ib = tool.snapshot_from_ddl("CREATE TABLE glue_catalog.lake.order_lines (order_line_id bigint, order_id int, quantity int, unit_price decimal(19,4), note string, created_at timestamp, line_total decimal(24,4), tag string) USING iceberg;\nCREATE TABLE glue_catalog.lake.legacy (id int, payload string) USING iceberg;", "spark")
        c = tool.compare(self.src, ib, "iceberg"); r = rows(c)
        self.assertEqual({r[k]["classification"] for k in ("OrderId", "Quantity", "UnitPrice", "Note", "Tag", "CreatedAt")}, {"APPROVED_TRANSFORM"})
        self.assertEqual(c["summary"]["CONFLICT"], 0); self.assertTrue(all(k["classification"] == "APPROVED_TRANSFORM" for k in c["keyFindings"]))
        ibv = tool.snapshot_from_ddl("CREATE TABLE glue_catalog.lake.legacy (id int, payload varchar(50)) USING iceberg;", "spark")
        self.assertEqual(rows(tool.compare(self.src, ibv, "iceberg"), "dbo.legacy")["Payload"]["classification"], "CONFLICT")

    def test_keys_tables_naming_order(self):
        """SC-T06 key sets compared per profile, missing/extra tables, naming profiles and explicit mapping, column-order differences, deterministic statuses [SC-17] [SC-19] [SC-20] [SC-21] [SC-22]"""
        bad = tool.compare(self.src, self.bad, "aurora")
        self.assertEqual(bad["status"], "BLOCKED"); self.assertEqual(bad["stopCodes"], ["TARGET_SCHEMA_DECISION_REQUIRED"])
        pk = [k for k in bad["keyFindings"] if "primary key" in k["reason"]]; self.assertEqual(pk[0]["classification"], "CONFLICT")
        self.assertEqual(bad["tables"]["dbo.legacy"]["classification"], "MISSING_TARGET"); self.assertEqual(bad["tableSummary"]["MISSING_TARGET"], 1)
        self.assertEqual(bad["tables"]["→ public.audit_only"]["classification"], "MISSING_SOURCE")
        missing_only = tool.compare(self.src, tool.snapshot_from_ddl(TGT_OK.split("CREATE TABLE public.legacy")[0], "pgsql"), "aurora")
        self.assertEqual(missing_only["status"], "PARTIAL"); self.assertEqual(missing_only["stopCodes"], ["STATIC_VALIDATION_FAILED"])
        # naming: preserve requires identical names; mapping fixes an intentional rename
        ren = tool.snapshot_from_ddl(TGT_OK.replace("note          VARCHAR(200)", "remark        VARCHAR(200)"), "pgsql")
        c = tool.compare(self.src, ren, "aurora"); self.assertEqual(rows(c)["Note"]["classification"], "MISSING_TARGET"); self.assertEqual(rows(c)["→remark"]["classification"], "MISSING_SOURCE")
        c = tool.compare(self.src, ren, "aurora", mapping={"columns": {"dbo.OrderLines": {"Note": "remark"}}})
        self.assertEqual(rows(c)["Note"]["classification"], "APPROVED_TRANSFORM"); self.assertIn("explicit mapping", rows(c)["Note"]["reason"])
        pres = tool.compare(self.src, self.ok, "aurora", naming="preserve")
        self.assertEqual(pres["tables"]["dbo.orderlines"]["classification"], "MISSING_TARGET")
        pres = tool.compare(self.src, self.ok, "aurora", naming="preserve", mapping={"tables": {"dbo.OrderLines": "public.order_lines", "dbo.Legacy": "public.legacy"}})
        self.assertEqual(rows(pres)["OrderId"]["classification"], "MISSING_TARGET")  # column names still differ under preserve
        # order
        reordered = tool.snapshot_from_ddl(TGT_OK.replace("    order_id      INTEGER NOT NULL,\n    quantity      SMALLINT NOT NULL,", "    quantity      SMALLINT NOT NULL,\n    order_id      INTEGER NOT NULL,"), "pgsql")
        c = tool.compare(self.src, reordered, "aurora")
        self.assertEqual(c["status"], "GENERATED"); self.assertEqual(len(c["orderDifferences"]), 1); self.assertEqual(c["orderDifferences"][0]["table"], "dbo.orderlines")
        live_like = json.loads(json.dumps(self.ok)); live_like["provenance"]["method"] = "live-information_schema"
        self.assertEqual(tool.compare(self.src, live_like, "aurora")["status"], "VALIDATED")

    def test_conform_refs_report_package(self):
        """SC-T07 conform proposals are dry-run DDL per dialect; refs resolves converted code against the target; report and package carry hashes and the validation manifest [SC-30] [SC-31] [SC-32] [SC-33]"""
        bad = tool.compare(self.src, self.bad, "aurora")
        sql = tool.conform_sql(bad, self.src)
        self.assertIn("-- DECISION: public.order_lines.line_total — computed column LineTotal", sql); self.assertIn("ALTER COLUMN order_line_id TYPE bigint", sql); self.assertIn("ALTER COLUMN unit_price TYPE numeric(19,4)", sql)
        self.assertIn("ALTER COLUMN tag TYPE text", sql); self.assertIn("-- DECISION: public.order_lines.note", sql); self.assertIn("-- DECISION: public.order_lines.extra_flag", sql)
        self.assertIn("-- DECISION: table dbo.legacy has no target table", sql); self.assertIn("DRY RUN", sql)
        ib = tool.compare(self.src, tool.snapshot_from_ddl("CREATE TABLE glue_catalog.lake.order_lines (order_line_id bigint) USING iceberg;", "spark"), "iceberg")
        self.assertIn("ALTER TABLE lake.order_lines ADD COLUMNS (unit_price decimal(19,4));", tool.conform_sql(ib, self.src))
        code = "CREATE OR REPLACE FUNCTION public.f(p_id INTEGER) RETURNS NUMERIC LANGUAGE plpgsql AS $$\nDECLARE v_total NUMERIC := 0;\nBEGIN\n WITH recent AS (SELECT * FROM public.order_lines WHERE order_id = p_id)\n SELECT SUM(r.unit_price) INTO v_total FROM recent r JOIN public.legacy l ON l.id = r.order_id;\n INSERT INTO public.ghost_table VALUES (1);\n RETURN v_total; END; $$;"
        missing = tool.check_refs(code, self.ok)
        self.assertEqual(missing, ["public.ghost_table"])
        f = self.tmp / "code.sql"; f.write_text(code, encoding="utf-8"); (self.tmp / "ok.json").write_text(tool.contract.canonical_json(self.ok), encoding="utf-8")
        rc, out = run("refs", str(f), "--target", str(self.tmp / "ok.json"), "--json"); self.assertEqual(rc, 1); self.assertIn("DEPENDENCY_UNRESOLVED", out)
        md = tool.report_md(bad)
        self.assertIn("**Status: BLOCKED**", md); self.assertIn("| CONFLICT |", md); self.assertIn("## Keys", md); self.assertIn(bad["sourceSnapshot"]["hash"][:12], md)
        (self.tmp / "src.json").write_text(tool.contract.canonical_json(self.src), encoding="utf-8"); (self.tmp / "bad.json").write_text(tool.contract.canonical_json(self.bad), encoding="utf-8")
        rc, out = run("compare", str(self.tmp / "src.json"), str(self.tmp / "bad.json"), "--profile", "aurora", "--out", str(self.tmp / "cmp")); self.assertEqual(rc, 1, out)
        rc, out = run("conform", str(self.tmp / "cmp" / "compare.json"), "--source", str(self.tmp / "src.json"), "--out", str(self.tmp / "fix.sql")); self.assertEqual(rc, 0, out)
        rc, out = run("package", str(self.tmp / "cmp" / "compare.json"), "--out", str(self.tmp / "pkg")); self.assertEqual(rc, 1, out)
        o = json.loads((self.tmp / "pkg" / "output.json").read_text(encoding="utf-8"))
        self.assertEqual(o["status"], "BLOCKED"); self.assertIn("TARGET_SCHEMA_DECISION_REQUIRED", o["analysis"]["stopCodes"])
        ex = {e["id"]: e["status"] for e in o["validation"]["executedChecks"]}
        self.assertEqual(ex["V-006"], "FAIL"); self.assertEqual(ex["V-009"], "FAIL"); self.assertTrue((self.tmp / "pkg" / "manifest.json").exists())
        self.assertTrue(o["analysis"]["manualReviewItems"])

    def test_project_regression(self):
        """SC-T08 this project's source/schema conforms to generated/schema.sql (aurora profile, 0 conflicts, no unresolved references in generated/); a live PostgreSQL target is compared when configured [SC-40] [SC-31]"""
        src = self.tmp / "p_src.json"; tgt = self.tmp / "p_tgt.json"
        rc, out = run("snapshot", str(ROOT / "source" / "schema"), "--dialect", "tsql", "--out", str(src)); self.assertEqual(rc, 0, out)
        rc, out = run("snapshot", str(ROOT / "generated" / "schema.sql"), "--dialect", "pgsql", "--out", str(tgt)); self.assertEqual(rc, 0, out)
        rc, out = run("compare", str(src), str(tgt), "--profile", "aurora", "--out", str(self.tmp / "p_cmp")); self.assertEqual(rc, 0, out)
        cmp = json.loads((self.tmp / "p_cmp" / "compare.json").read_text(encoding="utf-8"))
        self.assertEqual(cmp["status"], "GENERATED"); self.assertEqual(cmp["summary"]["CONFLICT"], 0); self.assertEqual(cmp["summary"]["MISSING_TARGET"], 0)
        self.assertEqual(cmp["tableSummary"]["matched"], 17)
        rc, out = run("refs", str(ROOT / "generated"), "--target", str(tgt)); self.assertEqual(rc, 0, out)
        db = os.environ.get("PGDATABASE", "")
        if os.environ.get("PGHOST") and tool.TEST_DB.search(db) and shutil.which("psql"):
            rc, out = run("snapshot", "--live", "--schema", "public", "--out", str(self.tmp / "live.json"))
            if rc == 0:
                rc, out = run("compare", str(src), str(self.tmp / "live.json"), "--profile", "aurora", "--out", str(self.tmp / "live_cmp")); self.assertEqual(rc, 0, out)
                self.assertEqual(json.loads((self.tmp / "live_cmp" / "compare.json").read_text(encoding="utf-8"))["status"], "VALIDATED")
            else:
                print(f"live snapshot skipped: {out.strip().splitlines()[-1:]}")


class TaggedResult(unittest.TextTestResult):
    lines = []

    def addSuccess(self, test):
        super().addSuccess(test); self.lines.append(("PASS", test))

    def addFailure(self, test, err):
        super().addFailure(test, err); self.lines.append(("FAIL", test))

    def addError(self, test, err):
        super().addError(test, err); self.lines.append(("ERROR", test))


if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--results"); a = ap.parse_args()
    suite = unittest.defaultTestLoader.loadTestsFromTestCase(SchemaTests)
    result = unittest.TextTestRunner(verbosity=2, resultclass=TaggedResult).run(suite)
    if a.results:
        with open(a.results, "a", encoding="utf-8") as f:
            for status, test in TaggedResult.lines:
                f.write(f"{status}\tschema\t{(test.shortDescription() or test.id()).strip()}\n")
    sys.exit(0 if result.wasSuccessful() else 1)
