-- ============================================================
-- informatica-etl-conversion skill — test fixtures
-- The PostgreSQL objects the worked-example mappings read or write besides the
-- shared sample schema: staging/dimension/fact/audit tables, the functions that
-- replace EXEC'd procedures and T-SQL Pre-SQL batches, and the stored procedure
-- called by the Stored Procedure transformation (a trimmed stand-in for the
-- project's public.calculate_shipping, converted by the sql-conversion skill).
-- ============================================================

CREATE TABLE public.stg_orders (
    order_id       INTEGER       NOT NULL PRIMARY KEY,
    customer_id    INTEGER       NOT NULL,
    customer_name  VARCHAR(201),
    total_amount   NUMERIC(19,4) NOT NULL,
    status         VARCHAR(50)   NOT NULL,
    order_date     TIMESTAMP(3)  NOT NULL,
    load_id        INTEGER       NOT NULL
);

CREATE TABLE public.etl_load_log (
    log_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  VARCHAR(128) NOT NULL,
    load_id     INTEGER      NOT NULL,
    logged_at   TIMESTAMP    NOT NULL DEFAULT clock_timestamp()
);

-- dbo.usp_LogLoad @TableName, @LoadId  →  SELECT public.etl_log_load(name, id)
CREATE FUNCTION public.etl_log_load(p_table_name VARCHAR(128), p_load_id INTEGER)
RETURNS INTEGER LANGUAGE plpgsql AS $$
DECLARE v_id INTEGER;
BEGIN
    INSERT INTO public.etl_load_log AS l (table_name, load_id) VALUES (p_table_name, p_load_id)
    RETURNING l.log_id INTO v_id;
    RETURN v_id;
END $$;

CREATE TABLE public.dim_customer (
    customer_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   INTEGER      NOT NULL,
    first_name    VARCHAR(100),
    last_name     VARCHAR(100),
    email         VARCHAR(255),
    is_current    BOOLEAN      NOT NULL DEFAULT TRUE,
    updated_at    TIMESTAMP
);
INSERT INTO public.dim_customer (customer_id, first_name, last_name, email) VALUES (1, 'Alice', 'Smith', '  alice@example.com  ');

CREATE TABLE public.stg_customer (
    customer_id  INTEGER NOT NULL,
    first_name   VARCHAR(100),
    last_name    VARCHAR(100),
    email        VARCHAR(255)
);
INSERT INTO public.stg_customer VALUES (1, 'Alice', 'Smith', 'alice@example.com'), (2, 'Bob', 'Jones', 'bob@example.com');

-- Replaces the T-SQL variable batch in the target Pre SQL (IC-10 / IC-11)
CREATE FUNCTION public.etl_pre_dim_customer() RETURNS INTEGER LANGUAGE plpgsql AS $$
DECLARE v_cnt INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM public.dim_customer;
    IF v_cnt = 0 THEN
        INSERT INTO public.dim_customer (customer_id, first_name, last_name, email, is_current)
        VALUES (-1, 'Unknown', 'Unknown', 'unknown@example.com', TRUE);
    END IF;
    RETURN v_cnt;
END $$;

CREATE TABLE public.fact_shipping (
    order_id           INTEGER PRIMARY KEY,
    shipping_cost      NUMERIC(19,4),
    last_order_amount  NUMERIC(19,4)
);

-- dbo.usp_ArchiveOldOrders @Days (Source Pre Load stored procedure) → function
CREATE TABLE public.orders_archive (LIKE public.orders);
CREATE FUNCTION public.archive_old_orders(p_days INTEGER) RETURNS INTEGER LANGUAGE plpgsql AS $$
DECLARE v_n INTEGER;
BEGIN
    INSERT INTO public.orders_archive
    SELECT o.* FROM public.orders o
    WHERE  o.created_at < LOCALTIMESTAMP - make_interval(days => p_days) AND o.status = 'Cancelled';
    GET DIAGNOSTICS v_n = ROW_COUNT;
    RETURN v_n;
END $$;

-- dbo.usp_CalculateShipping (connected Stored Procedure transformation).
-- Trimmed stand-in for the project's converted public.calculate_shipping.
CREATE FUNCTION public.calculate_shipping(p_order_id INTEGER, p_ship_to_zip VARCHAR(10), p_is_expedited BOOLEAN DEFAULT FALSE)
RETURNS TABLE(order_id INTEGER, shipping_cost NUMERIC(19,4))
LANGUAGE sql STABLE AS $$
    SELECT o.order_id,
           CASE WHEN o.total_amount >= 50 THEN 0
                ELSE ROUND(COALESCE(SUM(p.weight_lbs * ol.quantity), 0) * 1.10, 2) * CASE WHEN p_is_expedited THEN 1.5 ELSE 1 END
           END::NUMERIC(19,4)
    FROM   public.orders o
    JOIN   public.order_lines ol ON ol.order_id = o.order_id
    JOIN   public.products p ON p.product_id = ol.product_id
    WHERE  o.order_id = p_order_id
    GROUP  BY o.order_id, o.total_amount;
$$;

CREATE TABLE public.fact_product_sales (
    product_id    INTEGER      NOT NULL,
    period_start  TIMESTAMP(3) NOT NULL,
    units_sold    INTEGER,
    revenue       NUMERIC(19,4),
    PRIMARY KEY (product_id, period_start)
);

CREATE TABLE public.audit_load (
    audit_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_name  VARCHAR(100) NOT NULL,
    row_count  BIGINT       NOT NULL,
    loaded_at  TIMESTAMP    NOT NULL
);

-- ---------------------------------------------------------------- example 05 (real export format)
CREATE TABLE public.customer_segments (
    segment_code         VARCHAR(10)   NOT NULL PRIMARY KEY,
    min_lifetime_amount  NUMERIC(19,4) NOT NULL,
    is_active            BOOLEAN       NOT NULL
);
INSERT INTO public.customer_segments VALUES ('BRONZE', 0, TRUE), ('SILVER', 1000, TRUE), ('GOLD', 4000, TRUE), ('LEGACY', 500, FALSE);

CREATE TABLE public.stg_customer_summary (
    customer_id            INTEGER       NOT NULL PRIMARY KEY,
    customer_name          VARCHAR(201),
    order_count            INTEGER,
    lifetime_amount        NUMERIC(19,4),
    last_order_amount      NUMERIC(19,4),
    days_since_last_order  INTEGER,
    purchased_skus         VARCHAR(4000),
    segment_code           VARCHAR(10),
    load_id                INTEGER       NOT NULL,
    updated_at             TIMESTAMP
);
INSERT INTO public.stg_customer_summary (customer_id, load_id) VALUES (99, 41);   -- left over from a previous run: Pre SQL must truncate it

CREATE TABLE public.etl_run_log (
    run_log_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name     VARCHAR(128) NOT NULL,
    load_id      INTEGER      NOT NULL,
    started_at   TIMESTAMP    NOT NULL DEFAULT LOCALTIMESTAMP,
    ended_at     TIMESTAMP,
    rows_loaded  BIGINT,
    note         VARCHAR(200)
);

-- dbo.usp_EtlRunStart @JobName, @LoadId → SELECT public.etl_run_start(job, id)
CREATE FUNCTION public.etl_run_start(p_job_name VARCHAR(128), p_load_id INTEGER)
RETURNS INTEGER LANGUAGE plpgsql AS $$
DECLARE v_id INTEGER;
BEGIN
    INSERT INTO public.etl_run_log AS l (job_name, load_id) VALUES (p_job_name, p_load_id)
    RETURNING l.run_log_id INTO v_id;
    RETURN v_id;
END $$;
