-- Worked example 01 — Amazon Redshift DDL (design decisions from 01_sales_tables.design.json)
-- Ledger: RS-04 CHECK dropped · RS-15 NEWID default removed · RS-20/21 NVARCHAR bytes, MAX → 65535
--         RS-22 MONEY → DECIMAL(19,4) · RS-23 BIT → BOOLEAN · RS-24 UUID → VARCHAR(36) · RS-25 DATETIME2 → TIMESTAMP
--         RS-30 DISTSTYLE/SORTKEY decided · RS-31 indexes → sort keys · RS-32 PK/FK informational · RS-33 IDENTITY · RS-35 computed column
CREATE TABLE sales.dim_customer (
    customer_key   INTEGER IDENTITY(1,1) NOT NULL,
    customer_id    VARCHAR(36) NOT NULL,          -- TODO: MANUAL REVIEW REQUIRED — DEFAULT NEWID() has no equivalent; key generated by the load (RS-15)
    customer_name  VARCHAR(800) NOT NULL,         -- NVARCHAR(200) × 4 bytes for multibyte names (RS-20)
    region         VARCHAR(50) NOT NULL,          -- CHECK (region IN ('EMEA','AMER','APAC')) dropped: validate with V-009 (RS-04)
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    notes          VARCHAR(65535),
    created_at     TIMESTAMP NOT NULL DEFAULT GETDATE(),
    CONSTRAINT pk_dim_customer PRIMARY KEY (customer_key)      -- informational, not enforced
)
DISTSTYLE ALL
COMPOUND SORTKEY (customer_key);
-- filtered unique index UX_DimCustomer_Name (WHERE IsActive = 1) cannot be expressed: uniqueness proven by the V-014 query below (RS-31)

CREATE TABLE sales.fact_sales (
    sales_key      BIGINT IDENTITY(1,1) NOT NULL,
    customer_key   INTEGER NOT NULL,
    sale_date      DATE NOT NULL,
    quantity       SMALLINT NOT NULL,
    unit_price     DECIMAL(19,4) NOT NULL,
    line_total     DECIMAL(24,4) NOT NULL,        -- computed column materialized by the load: quantity * unit_price (RS-35)
    loaded_at      TIMESTAMP NOT NULL DEFAULT GETDATE(),
    CONSTRAINT pk_fact_sales PRIMARY KEY (sales_key),                                                    -- informational
    CONSTRAINT fk_fact_sales_customer FOREIGN KEY (customer_key) REFERENCES sales.dim_customer (customer_key)  -- informational
)
DISTSTYLE KEY
DISTKEY (customer_key)
COMPOUND SORTKEY (sale_date);

-- V-014 uniqueness proof for the informational keys and the dropped filtered index
SELECT customer_name, COUNT(*) FROM sales.dim_customer WHERE is_active GROUP BY customer_name HAVING COUNT(*) > 1;
SELECT sales_key, COUNT(*) FROM sales.fact_sales GROUP BY sales_key HAVING COUNT(*) > 1;
